---
apiVersion: v2
appVersion: version-5.6.14
description: "Firefly III: a personal finances manager"
name: firefly-iii
version: 0.0.2
kubeVersion: ">=1.16.0-0"
keywords:
  - firefly-iii
  - firefly
home: "https://github.com/k8s-at-home/charts/tree/master/charts/stable/firefly-iii"
icon: "https://www.firefly-iii.org/assets/logo/color.png"
sources:
  - https://github.com/firefly-iii/firefly-iii
maintainers:
  - name: "bikram990"
    url: "https://github.com/bikram990"
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.1
  - name: mariadb
    version: 11.0.9
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 11.1.29
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 16.9.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `mariadb` chart dependency to version 11.0.9
    - kind: changed
      description: Upgraded `postgresql` chart dependency to version 11.1.29
    - kind: changed
      description: Upgraded `redis` chart dependency to version 16.9.11
